spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tourist_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
  logging:
    level:
      org.springframework: INFO